apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "lsm"
spec:
  lsmhooks:
  - hook: "bprm_check_security"
    args:
      - index: 0
        type: "linux_binprm"
        extractParam: "mm.owner.real_parent.real_parent.comm"
        overwriteType: "string"
    selectors:
      - matchActions:
        - action: Post
